### ISSUE TITLE
Make BEEFY able to generate  data needed for Web3Sum proof generation

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-sdk#3]
This is an epic issue tracking the progress to make Substrate client to be able to generate all necessary data for a Web3Sum relay node so it is able to generate a succinct proof for state of a Substrate chain. The remaining steps are the following:
 
- [x] Implement BLS Core Crypto: https://github.com/paritytech/substrate/pull/13618
- [x] Make BLS primitives generic over the signature scheme: https://github.com/paritytech/substrate/pull/14373
- [x] Implement (ECDSA,BLS) crypto scheme: #1705
- [x] Implement Application crypto layer for (ECDSA, BLS): #1815
- [x] Make (ECDSA,BLS) crypto scheme to be able to sign with costum hasher: 2066.
- [x] Make BEEFY keystore be able to sign and verify (ECDSA,BLS): #2258.
- [x] Make the rest of BEEFY client generic over Keystore type so it could deal and gossip (ECDSA,BLS) signature: #1816 (need to be rebased to #2258 when it gets merged).
- [ ] Make validators sign the Web3Sum commitment to next validator set and include it in BEEFY payload.
